baseURL = "https://dilawar.github.io"
languageCode = "en-us"
title = "Dilawar's Blog"
theme = "ezhil"

# enable syntax highlighting.
pygmentsstyle = "solarized"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-180197482-1"
disqusShortname = "dilawarsblog"

paginate = 10
smmaryLength = 10

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "watch -n 1 /dev/null"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN
    # instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if
    # not defined.
    favicon = "icons/icon.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is
    # in dark mode.
    mode = "auto" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is
    # copied as it is to root by Hugo. For example if you have custom CSS file
    # under `static/css/custom.css` theen you can specify custom css path as
    # `css/custom.css`.
    customCSS = "css/custom.css"

    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can
    # place js files under `static/js` folder and specify path here as
    # `js/script-name.js`. You can also specify full url, for example you may
    # want to include external JS library.
    customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.  Uses feather icons for
# icons. You can [search icon names from here](https://feathericons.com/).

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/dilawar"

# Enable tags.
[taxonomies]
   tag = "tags"
