baseURL = "https://dilawar.github.io"
languageCode = "en-us"
title = "Dilawar's Blog"
author = "Dilawar Singh"
theme = "hugo-vitae"
enableRobotsTXT = true
copyright = "© 2021, Dilawar Singh"

custom_css = ["css/custom.css"]

[services.googleAnalytics]
id = "G-W9SB8FTCTQ"

[params]
    homepage = false
    math = true

    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "watch -n 1 /dev/null | moved to https://dilawars.notion.site"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]


[params.comments]
enabled = true
engine = "disqus"

[params.comments.disqus]
shortname = "dilawarsblog"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.  Uses feather icons for
# icons. You can [search icon names from here](https://feathericons.com/).

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/dilawar"

[[params.social]]
name = "Email"
icon = "fab fa-envelope"
cmd = "mailto:dilawar.s.rajput@gmail.com"


# Enable tags.
[taxonomies]
   tag = "tags"
   category = "categories"
   series = "series"

